### ISSUE TITLE
typo "remeber"   , more clarity

### ISSUE THREAD

**Issue by dimyme** [aprico-org/aprico-webext#1]
currently it reads:

It will be asked only once, but please, make sure to **remeber** it, there is no way to recover your ID.

for higher clarity, I suggest:

**The ID will be asked only once and right here. Make sure you remember it, since there is no way to recover your ID - meaning that all website-passwords are lost without this ID, which you are entering here.**

**Comment by pinoceniccola** [comment]
While this extension should be very easy to use, I'm aware that is lacking proper documentation. I'm working on it.

Meanwhile I added a bit of more clarity based on your suggestion and I'm currently pushing the update on the extension stores.

Thank you.
